
# this is supposed to use the default colors of the terminal
# instead of the tmux colors, but nothing changes
set-option -sa terminal-overrides ",xterm*:Tc"

set -g escape-time 0
set -g repeat-time 200

set -g mouse on

set-option -g focus-events on

# 1-based indexing on windows and panes
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# rebind <leader> to ctrl-Space
set -g prefix C-Space
unbind C-b
bind-key C-a send-prefix

# open window in same directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# vi key binds for copying
set-window-option -g mode-keys vi
# start copy mode with <prefix>-[ and navigate with vim navigation keys
# begin selecting with v
bind-key -T copy-mode-vi v send-keys -X begin-selection
# toggle line and rectangle selection with ctrl-v
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
# copy the selection with y
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# select panes with vim motions
bind-key -r h select-pane -L
bind-key -r j select-pane -D
bind-key -r k select-pane -U
bind-key -r l select-pane -R

# remap selecting the previous window since prefix-l has been remapped
bind-key \\ select-window -l

bind-key | command-prompt -p "Swap window:" "swap-window -t '%%'\; select-window -t '%1'"
