
# this is supposed to use the default colors of the terminal
# instead of the tmux colors, but nothing changes
set-option -sa terminal-overrides ",xterm*:Tc"

set -g escape-time 0
set -g repeat-time 200

set -g mouse on

# 1-based indexing on windows and panes
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# rebind <leader> to ctrl-Space
set -g prefix C-Space
unbind C-b
bind-key C-a send-prefix

# open window in same directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
